apiVersion: v1
kind: Namespace
metadata:
  name: aiplex-system
  labels:
    {{- include "aiplex.labels" . | nindent 4 }}
    istio.io/rev: asm-managed-rapid
---
apiVersion: v1
kind: Namespace
metadata:
  name: mcplex
  labels:
    {{- include "aiplex.labels" . | nindent 4 }}
    istio.io/rev: asm-managed-rapid
    aiplex.io/plane: mcplex
---
apiVersion: v1
kind: Namespace
metadata:
  name: a2aplex
  labels:
    {{- include "aiplex.labels" . | nindent 4 }}
    istio.io/rev: asm-managed-rapid
    aiplex.io/plane: a2aplex
---
apiVersion: v1
kind: Namespace
metadata:
  name: llmplex
  labels:
    {{- include "aiplex.labels" . | nindent 4 }}
    istio.io/rev: asm-managed-rapid
    aiplex.io/plane: llmplex
