apiVersion: v1
kind: Namespace
metadata:
  name: aiplex-system
  labels:
    istio.io/rev: asm-managed-rapid
    kubernetes.io/metadata.name: aiplex-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: mcplex
  labels:
    istio.io/rev: asm-managed-rapid
    kubernetes.io/metadata.name: mcplex
    aiplex.io/plane: mcplex
---
apiVersion: v1
kind: Namespace
metadata:
  name: a2aplex
  labels:
    istio.io/rev: asm-managed-rapid
    kubernetes.io/metadata.name: a2aplex
    aiplex.io/plane: a2aplex
---
apiVersion: v1
kind: Namespace
metadata:
  name: llmplex
  labels:
    istio.io/rev: asm-managed-rapid
    kubernetes.io/metadata.name: llmplex
    aiplex.io/plane: llmplex
